// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd94ktEfYihfAd0d4lewkYh3bUTYvSCUU',
    appId: '1:1041486632789:web:f2e9fd90a719092d8e81dc',
    messagingSenderId: '1041486632789',
    projectId: 'ngrent-b6a74',
    authDomain: 'ngrent-b6a74.firebaseapp.com',
    storageBucket: 'ngrent-b6a74.firebasestorage.app',
    measurementId: 'G-NX4NRQRFEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkSrpr65cOrl3gphLcpoxVaHsxTyjiPp0',
    appId: '1:1041486632789:android:41d631ba902ff0c38e81dc',
    messagingSenderId: '1041486632789',
    projectId: 'ngrent-b6a74',
    storageBucket: 'ngrent-b6a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG1TkydhDrZmOZNy2VwAcKEsE-tAow-JI',
    appId: '1:1041486632789:ios:05d6be1ee12c22498e81dc',
    messagingSenderId: '1041486632789',
    projectId: 'ngrent-b6a74',
    storageBucket: 'ngrent-b6a74.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG1TkydhDrZmOZNy2VwAcKEsE-tAow-JI',
    appId: '1:1041486632789:ios:05d6be1ee12c22498e81dc',
    messagingSenderId: '1041486632789',
    projectId: 'ngrent-b6a74',
    storageBucket: 'ngrent-b6a74.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd94ktEfYihfAd0d4lewkYh3bUTYvSCUU',
    appId: '1:1041486632789:web:b03ecc4bb048d1898e81dc',
    messagingSenderId: '1041486632789',
    projectId: 'ngrent-b6a74',
    authDomain: 'ngrent-b6a74.firebaseapp.com',
    storageBucket: 'ngrent-b6a74.firebasestorage.app',
    measurementId: 'G-KP5FGB3ZTS',
  );
}
